name: 'Deploy Action'
description: 'A reusable GitHub Action for deploying to different environments.'
inputs:
  ip:
    description: 'IP address for the environment'
    required: true
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  slack_channel_id:
    description: 'Slack notification channel ID'
    required: true
  ssh_private_key:
    description: 'SSH private key'
    required: true
  git_organization:
    description: 'Git organization'
    required: true
  deploy:
    description: 'Deploy to environment ? (true/false)'
    required: false
    default: 'false'
  stage:
    description: 'Stage name ? (recette/staging/prod)'
    required: true

runs:
  using: 'composite'
  steps:
    - id: slack
      if: ${{ inputs.deploy == 'true' }}
      uses: slackapi/slack-github-action@v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
      with:
        channel-id: ${{ inputs.slack_channel_id }}
        payload: |
          {
            "text": "<https://github.com/${{ github.repository }}|${{ github.repository }}> : Deployment started in branch `${{ github.ref_name }}` in stage `${{ inputs.stage }}` with ip address `${{ inputs.ip }}` (In Progress) - Build Link: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here for build details>",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
    
    - name: Checkout
      if: ${{ inputs.deploy == 'true' }}
      uses: actions/checkout@v3
    
    - uses: ruby/setup-ruby@v1
      if: ${{ inputs.deploy == 'true' }}
      with:
        ruby-version: '3.3'
        bundler-cache: true
      continue-on-error: true
    
    - name: Setup SSH Keys
      if: ${{ inputs.deploy == 'true' }}
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}
      continue-on-error: true
    
    - name: Deploy
      if: ${{ inputs.deploy == 'true' }}
      run: |
        BRANCH=master IP=${{ inputs.ip }} GIT_ORGANIZATION=${{ inputs.git_organization }} bundle exec cap ${{ inputs.stage }} deploy
      shell: bash
      continue-on-error: true
    
    - uses: slackapi/slack-github-action@v1.25.0
      if: inputs.deploy == 'true'
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
      with:
        channel-id: ${{ inputs.slack_channel_id }}
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "text": "Repository: <https://github.com/${{ github.repository }}|${{ github.repository }}> - Deployment Status in branch `${{ github.ref_name }}` in stage `${{ inputs.stage }}` with ip address `${{ inputs.ip }}`: ${{ job.status }} - Build Link: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here for build details>",
            "attachments": [
              {
                "pretext": "Deployment Status: ${{ job.status }}",
                "color": "${{ job.status == 'success' && '28a745' || 'ff0000' }}",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "${{ job.status == 'success' && 'Completed' || 'Failure' }}"
                  }
                ]
              }
            ]
          }
